#!/usr/bin/env bash
# Establish the git baseline BEFORE any code changes.
#  - healthcare (Marley): add `upstream` remote, create our dev branch off the pristine
#    version-16 checkout so upstream updates can still be pulled cleanly later.
#  - clinic_core: commit the scaffold as our baseline.
set -uo pipefail

BENCH="$HOME/projects/clinic-platform/backend/frappe-bench"

git config --global --get user.email >/dev/null 2>&1 || git config --global user.email "dev@clinic.local"
git config --global --get user.name  >/dev/null 2>&1 || git config --global user.name  "Clinic Platform Dev"
git config --global --add safe.directory '*' 2>/dev/null || true

echo "############ MARLEY (healthcare) ############"
cd "$BENCH/apps/healthcare"
echo "--- remotes ---"; git remote -v
echo "--- current branch / tag ---"
git rev-parse --abbrev-ref HEAD; git describe --tags 2>/dev/null
echo "--- working tree status (must be clean) ---"
git status --porcelain | head -20
[ -z "$(git status --porcelain)" ] && echo "CLEAN" || echo "!!! DIRTY -- investigate before branching"

# Name the pristine remote `upstream` for clarity (origin already points at earthians/marley).
git remote get-url upstream >/dev/null 2>&1 || git remote add upstream https://github.com/earthians/marley.git
echo "--- remotes after ---"; git remote -v

if git show-ref --verify --quiet refs/heads/clinic-dev; then
  echo "branch clinic-dev already exists"
else
  git branch clinic-dev
  echo "created branch clinic-dev (baseline = pristine upstream version-16)"
fi
echo "--- baseline commit ---"
git rev-parse HEAD

echo
echo "############ CLINIC_CORE ############"
cd "$BENCH/apps/clinic_core"
git status --porcelain | head
if [ -z "$(git log --oneline -1 2>/dev/null)" ]; then
  git add -A
  git commit -q -m "chore: scaffold clinic_core app baseline

Generated by 'bench new-app clinic_core' against frappe v16.33.1.
No custom logic yet -- this is the untouched baseline."
  echo "committed clinic_core baseline"
else
  echo "clinic_core already has commits:"
fi
git log --oneline -3
git rev-parse HEAD
